#!/bin/bash

set -euo pipefail

readonly helper=/usr/lib/stappmus-activity-monitor/activity-sampler

[[ $# -eq 0 ]] || exit 64
[[ -x $helper ]] || exit 77
exec sudo -n /usr/lib/stappmus-activity-monitor/activity-sampler --activity-process-power-reader
